apiVersion: apps/v1
kind: Deployment
metadata:
  name: intrallm-webui-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intrallm-webui-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: intrallm-webui-dev
    spec:
      volumes:
        - name: intrallm-webui-dev
          persistentVolumeClaim:
            claimName: intrallm-webui-dev
      containers:
        - name: intrallm-webui-dev
          image: 'peratchikannan/hs-public:intrallm-webui-dev-v55'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: PROMETHEUS_HOST
            value: "" # Enter Prometheus host IP before submitting the YAML
          imagePullPolicy: Always
          resources:
          volumeMounts:
            - name: intrallm-webui-dev
              mountPath: /app/backend/data

