apiVersion: apps/v1
kind: Deployment
metadata:
  name: intrallm-webui-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intrallm-webui-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: intrallm-webui-dev
    spec:
      volumes:
        - name: intrallm-webui-dev
          persistentVolumeClaim:
            claimName: intrallm-webui-dev
      containers:
        - name: intrallm-webui-dev
          image: 'peratchikannan/hs-public:intrallm-webui-dev-v55'
          ports:
            - containerPort: 8080
              protocol: TCPenv:
            - name: PROMETHEUS_HOST
              value: 
            - name: WEBUI_URL
              value: 
            - name: ENABLE_OAUTH_SIGNUP
              value: 'true'
            - name: MICROSOFT_REDIRECT_URI
              value: 
            - name: MICROSOFT_CLIENT_SECRET
              value: 
            - name: MICROSOFT_CLIENT_TENANT_ID
              value: 
            - name: MICROSOFT_CLIENT_ID
              value: 
            - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
              value: 'true'
            - name: OAUTH_SESSION_TOKEN_ENCRYPTION_KEY
              value: WEBUI_SECRET_KEY
            - name: OPENID_PROVIDER_URL
              value: 
          imagePullPolicy: Always
          resources:
          volumeMounts:
            - name: intrallm-webui-dev
              mountPath: /app/backend/data

