apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3
  namespace: default
  labels:
    app: qwen3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3
  template:
    metadata:
      labels:
        app: qwen3
    spec:
      nodeName: node3
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm-storage
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Qwen/Qwen3-32B --served-model-name Intrallm/Intrallm-v1 --tensor-parallel-size 2 --no-disable-sliding-window --enable-auto-tool-choice --tool-call-parser hermes --max_model_len 34352"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        - name: NCCL_P2P_DISABLE
          value: "1"
        - name: VLLM_PORT
          value: "80"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "10"
            memory: 20G
            nvidia.com/gpu: "2"
          requests:
            cpu: "2"
            memory: 6G
            nvidia.com/gpu: "2"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
